---
new_page_extension: html
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
upload_dir: _assets/img
public_path: "/_assets/img"
front_matter_path: "/_assets/img"
use_front_matter_path: false
file_template: ":filename:"
